Mi scheduler/feature/kebechet merge
thoth-station/thoth-application pull request #1160
Opened 2021-04-12 12:24 UTC by xtuchyna

## Related Issues and Dependencies
Related to https://github.com/thoth-station/mi-scheduler/issues/99

## This introduces a breaking change

- [ ] Yes
- [ ] No

## Test or Stage Environment

- [ ] Pull Requests added content to STAGE environment
- [ ] Pull Requests to `AICoE/aicoe-cd` has been opened: 

## This Pull Request implements
New cronjob that schedules kebechet statistics merge

2021-04-12 12:28 UTC, xtuchyna commented
/kind WIP

2021-04-12 12:40 UTC, goern commented
/hold

2021-04-12 12:46 UTC, goern commented
/test all

2021-04-12 12:48 UTC, goern commented
/unhold

2021-04-12 12:48 UTC, goern commented
/test all

2021-04-12 13:02 UTC, goern commented
/test all

2021-04-12 13:45 UTC, harshad16 commented
/test all

2021-04-12 13:48 UTC, sesheta commented
@xtuchyna: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 403b58abc1387d0fdf561f29d917ea104b6d7d41 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--36f9ca3b-f5af-4432-bef8-af42508b403e/prow-logs/pr-logs/pull/thoth-station_thoth-application/1160/kustomize-build/1381604442733809664) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=1160). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Axtuchyna). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-04-12 14:35 UTC, xtuchyna commented
/retest

2021-04-12 14:36 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-04-12 14:37 UTC, xtuchyna commented
/assign @pacospace

2021-04-12 14:37 UTC, xtuchyna commented
/cc @pacospace

2021-04-12 17:53 UTC, xtuchyna commented
/cc @fridex

2021-04-12 20:32 UTC, xtuchyna commented
Hello @pacospace could you please have a look at this?

2021-04-13 02:23 UTC, harshad16 requested changes
all lgtm, just one change.

2021-04-13 02:23 UTC, harshad16 commented on mi-scheduler/base/cronjob.yaml
> +  suspend: false
can you suspend all cronjob in base 
and use the cronjob in individual overlays to suspend them.

please also include the cronjob mi-scheduler-kebechet-merge in all the overlays.

2021-04-13 02:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **pacospace** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @pacospace` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->

2021-04-23 11:20 UTC, goern commented
@xtuchyna any movement on this? what do we need to do to merge it?

2021-06-06 20:40 UTC, sesheta commented
@xtuchyna: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-06-08 12:39 UTC, xtuchyna commented
#oops this was introduced and fixed in other PR that is already merged https://github.com/thoth-station/thoth-application/pull/1500
We can close this.
/close

2021-06-08 12:39 UTC, sesheta commented
@xtuchyna: Closed this PR.

<details>

In response to [this](https://github.com/thoth-station/thoth-application/pull/1160#issuecomment-856730144):

>#oops this was introduced and fixed in other PR that is already merged https://github.com/thoth-station/thoth-application/pull/1500
>We can close this.
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-06-08 12:39 UTC, closed without merging