WIP: Introduce purge-job
thoth-station/thoth-application pull request #1208
Opened 2021-04-28 11:54 UTC by fridex

## Related Issues and Dependencies

Related: https://github.com/thoth-station/purge-job/

## Does this require new deployment ?

- [x] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`.

## Description

Purging old data out of a Thoth deployment.

2021-04-28 11:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-04-28 11:59 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 9c468f427aaac77aae3ca6b9594540f21b039ef6 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--36f9ca3b-f5af-4432-bef8-af42508b403e/prow-logs/pr-logs/pull/thoth-station_thoth-application/1208/kustomize-build/1387374593550848000) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=1208). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-05 18:59 UTC, fridex commented
@harshad16 PTAL, tested in test environment, looks operational 🤞🏻 

/assign @harshad16

2021-05-05 19:03 UTC, harshad16 approved these changes
lgtm,
thanks :100:

2021-05-05 19:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/1208#pullrequestreview-652651491" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-05 19:03 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | d289f8f5d516528d2a31fe2dd450e9fc2a8731d5 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--36f9ca3b-f5af-4432-bef8-af42508b403e/prow-logs/pr-logs/pull/thoth-station_thoth-application/1208/kustomize-build/1390018314792603648) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=1208). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-05-05 19:05 UTC, harshad16 requested changes

2021-05-05 19:05 UTC, harshad16 commented on purge-job/base/kustomization.yaml
> +  - openshift-templates/purge-template.yaml
oh the name different.
```suggestion
  - openshift-templates/purge.yaml
```

2021-05-05 19:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-05-05 19:05 UTC, fridex commented on purge-job/base/kustomization.yaml
> +  - openshift-templates/purge-template.yaml
Thanks, adjusted 👍🏻

2021-05-05 19:17 UTC, harshad16 approved these changes
thanks :100:

2021-05-05 19:17 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/1208#pullrequestreview-652662912" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-05 19:18 UTC, merged