imagetag updates
thoth-station/thoth-application pull request #1224
Opened 2021-05-03 09:57 UTC by goern

- add-ist is now configurable via ENV TEST-INFRA-IMAGE-TAG
- :arrow_up: standard updates of imagestreamtags of prow

2021-05-03 09:57 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **goern** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[prow/OWNERS](https://github.com/thoth-station/thoth-application/blob/master/prow/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2021-05-04 20:02 UTC, harshad16 requested changes
/lgtm
minor chnages required can please update the image kind.
any image coming from outside of cluster, is to have kind: DockerImage.

2021-05-04 20:02 UTC, harshad16 commented on prow/overlays/cnv-prod/imagestreamtags.yaml
> +        kind: ImageStreamTag
```suggestion
        kind: DockerImage
```

2021-05-04 20:02 UTC, harshad16 commented on prow/overlays/cnv-prod/imagestreamtags.yaml
> +        kind: ImageStreamTag
```suggestion
        kind: DockerImage
```

2021-05-04 20:02 UTC, harshad16 commented on prow/overlays/cnv-prod/imagestreamtags.yaml
> +        kind: ImageStreamTag
```suggestion
        kind: DockerImage
```

2021-05-04 20:02 UTC, harshad16 commented on prow/overlays/cnv-prod/imagestreamtags.yaml
> +        kind: ImageStreamTag
```suggestion
        kind: DockerImage
```

2021-05-04 20:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/1224#pullrequestreview-651615353" title="LGTM">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[prow/OWNERS](https://github.com/thoth-station/thoth-application/blob/master/prow/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-17 18:14 UTC, sesheta commented
@goern: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-28 08:21 UTC, goern commented
let's redo the update after the #1223 is merged

/close

2021-05-28 08:21 UTC, closed without merging