Add manifests needed for prescriptions-refresh
thoth-station/thoth-application pull request #1927
Opened 2021-08-27 14:17 UTC by fridex

## Description

Introduce [prescriptions-refresh](https://github.com/thoth-station/prescriptions-refresh-job) CronWorkflow.

2021-08-30 07:04 UTC, fridex commented
Ready to be reviewed. PTAL.

To make this work properly in stage and prod, Kebechet secrets will need to be deployed into the mentioned namespaces as well.

/assign @harshad16

2021-08-31 15:26 UTC, harshad16 requested changes
- Remove **overlays** from the **base** directory.
- change **cnv-prod** to **zero-prod**

2021-08-31 15:26 UTC, harshad16 commented on prescriptions-refresh-job/base/overlays/test/job-generate-name.yaml
> +  value: "thoth-middletier-stage"
```suggestion
  value: "thoth-test-core"
```

2021-08-31 18:08 UTC, fridex commented
@harshad16 Adjusted based on the review, thanks 👍🏻 PTAL

2021-09-07 12:20 UTC, harshad16 commented on prescriptions-refresh-job/overlays/ocp4-stage/job-generate-name.yaml
> +  value: "thoth-middletier-stage"
```suggestion
  value: "thoth-infra-stage"
```

2021-09-07 12:21 UTC, harshad16 commented on prescriptions-refresh-job/overlays/test/job-generate-name.yaml
> +  value: "thoth-middletier-stage"
```suggestion
  value: "thoth-infra-stage"
```

2021-09-07 12:22 UTC, harshad16 reviewed
lgtm
thanks

2021-09-07 12:22 UTC, harshad16 commented on prescriptions-refresh-job/overlays/test/job-generate-name.yaml
> +  value: "thoth-infra-stage"
```suggestion
  value: "thoth-test-core"
```

2021-09-07 12:22 UTC, harshad16 commented on prescriptions-refresh-job/overlays/zero-prod/job-generate-name.yaml
> +  value: "thoth-middletier-prod"
```suggestion
  value: "thoth-infra-prod"
```

2021-09-07 12:23 UTC, merged