Add prescription refresh workflow for image analysis handler
thoth-station/thoth-application pull request #2230
Opened 2021-12-22 11:47 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

2021-12-22 11:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **pacospace** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->

2021-12-22 11:48 UTC, pacospace commented
/hold for testing

2021-12-22 11:49 UTC, fridex approved these changes
lgtm! 👍🏻 🥇

2021-12-22 11:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/2230#pullrequestreview-838375438" title="Approved">fridex</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-10 10:35 UTC, pacospace commented
/retest

2022-01-10 10:55 UTC, goern commented
looks nice to me, can this go into next release?
/milestone 2022.01.18

2022-01-10 10:55 UTC, sesheta commented
@goern: The provided milestone is not valid for this repository. Milestones in this repository: [`2022.01.17`]

Use `/milestone clear` to clear the milestone.

<details>

In response to [this](https://github.com/thoth-station/thoth-application/pull/2230#issuecomment-1008753989):

>looks nice to me, can this go into next release?
>/milestone 2022.01.18


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-01-10 10:55 UTC, goern commented
/milestone 2022.01.17

2022-01-10 11:20 UTC, pacospace commented
/deploy

2022-01-10 14:59 UTC, harshad16 requested changes
lgtm
just few minor chnages required.

2022-01-10 14:59 UTC, harshad16 commented on prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
> +        name: quay.io/thoth-station/prescriptions-refresh-job:kebechet-v0.5.0
```suggestion
        name: quay.io/thoth-station/prescriptions-refresh-job:v0.5.0
```
This image is now available

2022-01-10 14:59 UTC, harshad16 commented on prescriptions-refresh-job/overlays/ocp4-stage/thoth-notification.yaml
> +            - "{'text':'Successfully synchronized *prescriptions-refresh-job* to *OCP4-STAGE*, see <https://argocd.operate-first.cloud/applications/prod-thoth-prescriptions-refresh-job|ArgoCD UI> 🚚'}
```suggestion
            - "{'text':'Successfully synchronized *prescriptions-refresh-job* to *OCP4-STAGE*, see <https://argocd.operate-first.cloud/applications/stage-thoth-prescriptions-refresh-job|ArgoCD UI> 🚚'}"
```

2022-01-10 15:08 UTC, harshad16 approved these changes
/unhold
thanks :100:

2022-01-10 15:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/2230#pullrequestreview-838375438" title="Approved">fridex</a>*, *<a href="https://github.com/thoth-station/thoth-application/pull/2230#pullrequestreview-847941028" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [fridex,harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-10 15:21 UTC, merged