Add Kafka offset and broker panels in smaug-prod dashboard
thoth-station/thoth-application pull request #2305
Opened 2022-02-02 10:12 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

2022-02-02 10:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **pacospace** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->

2022-02-02 15:12 UTC, harshad16 requested changes
lgtm
thanks for bring in the new chnages

2022-03-09 21:50 UTC, goern commented
/assign @pacospace

2022-03-10 10:10 UTC, closed without merging

2022-03-10 10:45 UTC, pacospace commented
Closing because of changes in https://github.com/thoth-station/thoth-application/pull/2362