Split prescriptions-refresh CronWorkflow to multiple CronWorkflows
thoth-station/thoth-application pull request #2312
Opened 2022-02-02 23:51 UTC by fridex

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/thoth-application/issues/2188
Fixes: https://github.com/thoth-station/thoth-application/issues/2281

2022-02-02 23:51 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-02-04 07:36 UTC, goern commented
/unassign @goern 
/assign @Gregory-Pereira

2022-02-08 03:37 UTC, Gregory-Pereira commented
Haven't worked with CronWorkflows before, working on the review but might take me some time to understand the `perscription-refresh-job`.

2022-02-19 18:59 UTC, fridex commented
Based on the discussion we had:

/assign @harshad16

2022-02-21 15:57 UTC, goern commented
@fridex @harshad16 @codificat do we target this for this or next milestone?

2022-02-21 16:25 UTC, harshad16 commented
yes we are

2022-02-21 22:38 UTC, harshad16 requested changes
lgtm
thanks for the awesome pr.

some minor changes are required as suggested and also we need add some more image patches.
I will try to add an extra commit in this pr to address all these changes. if it is okay with you we can proceed or feel free to pull the pr and adjust it as you feel.

2022-02-21 22:38 UTC, harshad16 commented on prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
> +              value: 1
```suggestion
              value: "1"
```

int values are not accepted.

2022-02-21 22:38 UTC, harshad16 commented on prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
> +                  name: prescription-refresh-job
```suggestion
                  name: prescriptions-refresh-job
```

2022-02-21 23:02 UTC, harshad16 commented on prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
> +              value: 1
Fixed in https://github.com/thoth-station/thoth-application/pull/2312/commits/eee94e2dc151a5a32ecf5b897ca49259e99ff63b

2022-02-21 23:03 UTC, harshad16 commented on prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
> +                  name: prescription-refresh-job
Fixed in https://github.com/thoth-station/thoth-application/pull/2312/commits/eee94e2dc151a5a32ecf5b897ca49259e99ff63b

2022-02-21 23:05 UTC, harshad16 commented
@fridex  TAL at https://github.com/thoth-station/thoth-application/pull/2312/commits/eee94e2dc151a5a32ecf5b897ca49259e99ff63b commit
I have tested it out in the test cluster it works.

we would have to monitor the mem, as the pods are running into oom.
I will do some more testing and make changes in another commit.

2022-02-21 23:07 UTC, fridex commented
> @fridex TAL at [eee94e2](https://github.com/thoth-station/thoth-application/commit/eee94e2dc151a5a32ecf5b897ca49259e99ff63b) commit I have tested it out in the test cluster it works.
> 
> we would have to monitor the mem, as the pods are running into oom. I will do some more testing and make changes in another commit.

Perfect! 💯 Changes look really good to me, feel free to merge based on your preferences 👍🏻

2022-02-21 23:12 UTC, harshad16 approved these changes
thanks for the amazing pr
lgtm :100:

2022-02-21 23:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/2312#pullrequestreview-889156218" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-02-21 23:15 UTC, merged