Increase adviser memory limit and requests
thoth-station/thoth-application pull request #2375
Opened 2022-02-23 21:59 UTC by fridex

## Related Issues and Dependencies

Related: https://github.com/thoth-station/adviser/issues/2272

## Description

Let's increase memory requests and limits. I'm not sure if this will help, but worth trying. I think we will need to do some optimization here (either adjusting heuristics or checking memory consumption of objects on adviser side). This is a very first attempt to check what's wrong.

2022-02-23 21:59 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **fridex** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[adviser/OWNERS](https://github.com/thoth-station/thoth-application/blob/master/adviser/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-02-24 01:07 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | ec0f2763218fe2f72ecfe28d62b70766b391456d | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2375/pre-commit/1496612819494244352) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2375). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-24 09:53 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | ec0f2763218fe2f72ecfe28d62b70766b391456d | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2375/pre-commit/1496612819494244352) | true | `/test pre-commit`
aicoe-ci/prow/kustomize-build | ec0f2763218fe2f72ecfe28d62b70766b391456d | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2375/kustomize-build/1496773535576625152) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2375). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-24 15:35 UTC, harshad16 commented
/test all

2022-02-24 15:55 UTC, harshad16 requested changes
Ack on the change.
However this would be overrided as we patch resources in overlays 
please update this files : https://github.com/thoth-station/thoth-application/blob/master/adviser/overlays/aws-prod/advise-resources-patch.yaml

Also our test cluster doesn't have such resource, that why we have individual patch in the system.

2022-02-28 18:35 UTC, fridex commented
Thanks. I will try to experiment with one memory optimization in adviser. Let's see if it will work 👍🏻 

/close

2022-02-28 18:35 UTC, closed without merging

2022-02-28 18:35 UTC, sesheta commented
@fridex: Closed this PR.

<details>

In response to [this](https://github.com/thoth-station/thoth-application/pull/2375#issuecomment-1054548027):

>Thanks. I will try to experiment with one memory optimization in adviser. Let's see if it will work 👍🏻 
>
>/close
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>