creating cron-workflow to invoke job template for the sync-job
thoth-station/thoth-application pull request #2524
Opened 2022-04-20 18:23 UTC by Gregory-Pereira

## Related Issues and Dependencies

Partially Addresses: https://github.com/thoth-station/thoth-application/issues/2513
Related to: https://github.com/thoth-station/sync-job/pull/61

## Does this require new deployment ?

- [ ] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`.

## Description

Creating a cron-workflow for the sync-job

/cc @harshad16

2022-04-20 18:23 UTC, sesheta commented
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

2022-04-20 18:23 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **goern** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @goern` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2022-04-20 18:24 UTC, Gregory-Pereira commented
I know that when going from stage to production we should be syncing adviser, revsolver, and security-indicator documents, but what about from production to stage?

2022-04-22 16:22 UTC, harshad16 requested changes
good start
i have added some suggestions.

2022-04-22 16:22 UTC, harshad16 commented on sync-job/base/cron-worfklow.yaml
> +        args: ["-p IMAGE_VERSION=$IMAGE_VERSION", "-p THOTH_SYNC_FORCE=$THOTH_SYNC_FORCE", "-p THOTH_SYNC_GRACEFUL=$THOTH_SYNC_GRACEFUL", "-p THOTH_SYNC_DEBUG=$THOTH_SYNC_DEBUG", "-f openshift.yaml",
This is not needed.
There is concept of source-to-image , the entrypoint is already set to the run script that can `app.py` and others based on the programming language. The pointer to different script can be done via setting env vars
https://docs.openshift.com/dedicated/3/using_images/s2i_images/python.html#using-images-python-configuration

2022-04-22 16:22 UTC, harshad16 commented on sync-job/base/cron-worfklow.yaml
> +            value: v0.2.3-dev
This is not needed.
this was used on the sync-job template and is not a part of the application itself. 
https://github.com/thoth-station/sync-job/blob/f630e32b9b62b0e81879a16f95ea34b7e1dadce8/openshift.yaml#L79

2022-04-22 16:22 UTC, harshad16 commented on sync-job/base/openshift.yaml
> +                  cpu: 4
The workflow would do the work of the job, 
we won't require a separate job.
the cronworkflow would schedule workflow as needed. 

Move all these env vars to the cronworkflow.

2022-04-22 19:49 UTC, Gregory-Pereira commented
It uses 3 templates because both for prod and stage, there are 3 separate types of documents to be synced. Additionally I can apply the resources (it is correct YAML syntax), however, the workflow controller rejects this `CronWorkflow` by giving me the following error: `"Unable to convert unstructured to CronWorkflow when syncing CronWorkflows" error="cannot restore slice from map"`

2022-04-26 23:23 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | bff2b7bfff0e14a6829825bfcfecdf611de7689e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/pre-commit/1519093740612882432) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-28 14:53 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 6c828b934f9cd5484582645391f92830fa607bec | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1519689931146924032) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-28 15:02 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | e431284fa86642983dd418b875aea3e6bddebb8c | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1519691903728095232) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-28 17:09 UTC, Gregory-Pereira commented
Cron-workflow is now accepted, ready for review.

2022-05-02 21:14 UTC, Gregory-Pereira commented
Attempting to implement this with a cron-workflow which uses a workflow template so the changes be used to both invoke a cronworkflow to run sync-job periodically, as well as be invoked from the management api via workflow. That being said I am encountering an Argo issue: `template reference exceeded max depth (10)`.

2022-05-02 21:18 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | c8f27e97d74d21e1e1dfd79e69146940cae6a11e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1521236186482348032) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-02 21:19 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | c8f27e97d74d21e1e1dfd79e69146940cae6a11e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1521236186482348032) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | c8f27e97d74d21e1e1dfd79e69146940cae6a11e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/pre-commit/1521236185647681536) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-02 21:36 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 5c9ec504d94baf66488b667a9722e6df9d121c9e | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1521238897693036544) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-03 03:25 UTC, Gregory-Pereira commented
Issue about template reference exceeding max depth has been resolved, hoping that @harshad16 could take a look when you have time.

2022-05-05 17:31 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 86c0fc0da7006ab2a8b1f2bb275b1bb4af17b67b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/kustomize-build/1522265757671493632) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 86c0fc0da7006ab2a8b1f2bb275b1bb4af17b67b | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_thoth-application/2524/pre-commit/1522265757252063232) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2524). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-06 17:02 UTC, harshad16 approved these changes
/lgtm
/approve
thanks :100:

2022-05-06 17:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/2524#pullrequestreview-964925435" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-05-06 17:13 UTC, merged