Include the info on different environments
thoth-station/thoth-application pull request #2647
Opened 2022-09-01 19:13 UTC by harshad16

Include the info on different environments
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: https://github.com/thoth-station/thoth-application/issues/2477

2022-09-01 19:13 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **harshad16** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-09-09 14:30 UTC, VannTen requested changes

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +This environment is used as a temperory production, it is on the same standard as production in term of resources,
```suggestion
This environment is used as a temporary production, it is on the same standard as production in term of resources,
```

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +## Prod Environments
```suggestion
## Prod Environment
```
Might use the singular ? AFAICT it's one env right ?

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +## Semi-Prod Environments
Same as above

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +## Stage Environments
Same as above

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +The Test environments are volatail and can be multiple at a give point of time, however devs can deploy there own if needed on the quicklab cluster (read here for more). The hosted test environment b
```suggestion
The Test environments are volatile and can be multiple at any given point in time, however devs can deploy their own if needed on the quicklab cluster (read here for more). The hosted test environment by team can be broken at any time, and ArgoCD is not set on self-healing or pruning of resources.<br>
The test environment consists of one OpenShift project, uses an ephemeral PostgreSQL deployment inside of that project, and depends on an external Kafka Broker deployment.<br>
```
spell.

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +The Test environments are volatail and can be multiple at a give point of time, however devs can deploy there own if needed on the quicklab cluster (read here for more). The hosted test environment b
Also, what exactly does it mean that test environments can be multiple at any given in time ? Shouldn't we simply document what exists ?

2022-09-09 14:30 UTC, VannTen commented on docs/environments.md
> +- we manage the storage via different project Thoth components which utlises the [thoth-storage](https://pypi.org/project/thoth-storages/) module. [Details](https://github.com/thoth-station/storages#
```suggestion
- we manage the storage via different project Thoth components which utlises the [thoth-storages](https://pypi.org/project/thoth-storages/) module. [Details](https://github.com/thoth-station/storages#thoth-storages)
```

2022-09-13 07:50 UTC, VannTen commented
Something else I just thought about: it seems to me we often refer to environment by their "surname" (aka "balrog", "smaug" etc). Maybe we should include in the section titles those names ?
(Like
`## Prod Environment (aka Balrog)` etc

2022-09-19 14:58 UTC, VannTen commented on docs/environments.md
Not sure if several "Credentials" section would conflict though (on the anchor level I mean)

2023-02-09 14:53 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from harshad16 by writing `/assign @harshad16` in a comment. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2023-02-09 15:01 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | ccb94c85da1608b1cd83d60a3fa7a7aa2cff0170 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/thoth-station_thoth-application/2647/pre-commit/1623696455803867136) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=2647). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-09 15:42 UTC, codificat commented
pre-commit failure (logging here in case logs disappear):

```
 trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook
Fixing docs/environments.md
```

2023-02-10 22:18 UTC, harshad16 commented
/hold

2023-05-29 09:16 UTC, closed without merging