Adjust web concurrency for management-api and amun-api
thoth-station/thoth-application pull request #993
Opened 2021-02-25 23:24 UTC by fridex

## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/pull/992

Let's see if the linked issue fixes the problem.

## This introduces a breaking change

- [x] No

2021-02-25 23:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-02-25 23:24 UTC, sesheta commented
@fridex: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 7eb33c8b79a12efe6e889886812bbc5699a8e641 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365080206477365248) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-25 23:24 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 7eb33c8b79a12efe6e889886812bbc5699a8e641 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365080206477365248) | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 7eb33c8b79a12efe6e889886812bbc5699a8e641 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365080206506725376) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-25 23:24 UTC, fridex commented
/hold

2021-02-26 08:27 UTC, goern requested changes

2021-02-26 08:27 UTC, goern commented on amun/base/deploymentconfig.yaml
> +￼              value: "2"
a space too much?!

2021-02-26 08:29 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 7eb33c8b79a12efe6e889886812bbc5699a8e641 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365080206506725376) | `/test pre-commit`
aicoe-ci/prow/kustomize-build | ed45b634d91ea1003c5715b12a542dba561f20fc | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365217228974198784) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-26 08:29 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | ed45b634d91ea1003c5715b12a542dba561f20fc | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365217228974198784) | `/test kustomize-build`
aicoe-ci/prow/pre-commit | ed45b634d91ea1003c5715b12a542dba561f20fc | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365217229007753216) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-26 08:31 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | ed45b634d91ea1003c5715b12a542dba561f20fc | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365217228974198784) | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 04bc173dc5bdf8934da2b9fdeb8c5d84e0b3f0e2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365217856559517696) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-02-26 08:36 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 04bc173dc5bdf8934da2b9fdeb8c5d84e0b3f0e2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365217856559517696) | `/test pre-commit`
aicoe-ci/prow/kustomize-build | 04bc173dc5bdf8934da2b9fdeb8c5d84e0b3f0e2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1365218947112112128) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-01 08:17 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 04bc173dc5bdf8934da2b9fdeb8c5d84e0b3f0e2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1365217856559517696) | `/test pre-commit`
aicoe-ci/prow/kustomize-build | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1366301368029024256) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-01 08:17 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1366301368029024256) | `/test kustomize-build`
aicoe-ci/prow/pre-commit | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1366301368049995776) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-02 08:13 UTC, goern commented
/assign @fridex

2021-03-03 14:46 UTC, fridex commented
/retest

2021-03-03 14:47 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1366301368049995776) | `/test pre-commit`
aicoe-ci/prow/kustomize-build | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1367124356014018560) | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-03 14:47 UTC, sesheta commented
@fridex: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/kustomize-build | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/kustomize-build/1367124356014018560) | `/test kustomize-build`
aicoe-ci/prow/pre-commit | e391587c61543d5124329cc9999709648893cb2d | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--5de4780e-313e-46c0-8758-209adf0ea179/prow-logs/pr-logs/pull/thoth-station_thoth-application/993/pre-commit/1367124356039184384) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=thoth-application&pr=993). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/thoth-application/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-03-03 16:16 UTC, fridex commented
PTAL ready to be merged.

2021-03-03 16:46 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/thoth-application/pull/993#issuecomment-789868632" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fthoth-application).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/thoth-application/blob/master/OWNERS)~~ [harshad16]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-03 18:41 UTC, goern commented
@fridex can we unhold this?

2021-03-03 19:35 UTC, harshad16 commented
/unhold

2021-03-03 19:36 UTC, merged